import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'
import React from 'react'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
   subsets: ["latin"],
 });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
 variable: "--font-geist-mono",
  subsets: ["latin"],
});


const unbounded = localFont({
  src: '../public/fonts/Unbounded-SemiExpanded.woff2',
  variable: '--font-heading',
})
const fira = localFont({
  src: '../public/fonts/FiraSans-Regular.woff2',
  variable: '--font-body',
})
export const metadata: Metadata = {
  title: "PLUK",
  description: "Generated by PLUK",
};

export default function RootLayout({ children }) {

  return (

    <html lang="es">
      <body className="bg-pluk-bg text-pluk-light">{children}</body>
    </html>
  )
}